### ISSUE TITLE
Kurzbeschreibung erstellen

### ISSUE THREAD

**Issue by eliareutlinger** [eliareutlinger/M151-Project#19]
Kurzbeschreibung der Anwendung für den META-TAG Description und die Startseite aus min. 60 Wörtern bidde. Dange. bitte

**Comment by vaekek** [comment]
Fitness Under Control ist deine Lösung den Papierkram endlich loszuwerden.
Wir bieten Lösung welche dir die Möglichkeit gibt deine Trainingspläne online zu verwalten. Du kannst eigene Übungen erfassen, eigene Pläne erstellen und Pläne anderer User verwenden.

**Comment by vaekek** [comment]
efnedim
